### ISSUE TITLE
项目的WEB API制作好以后，支持导出和导入么？

### ISSUE THREAD

**Issue by tyonly** [lixingdecai/api-doc#2]
比如 制作好了一个API，由于某些原因需要批量修改一个参数的名字，那么需要导出所有的API，修改好之后再导入进来，这样支持么

**Comment by lixingdecai** [comment]
如果是频繁批量修改一个参数的名字，那你的API设计的就是有问题了。批量修改参数不会出现在管理平台上面，会存在很大风险也没有做这个功能的必要。如果要批量修改，只能通过操作数据库噢

**Comment by lixingdecai** [comment]
导入 导出这个功能还没有做呢

**Comment by tyonly** [comment]
使用你的项目导出功能已经实现了 批量修改在导入的功能了

**Comment by lixingdecai** [comment]
赞
